### ISSUE TITLE
Security: Better way to use streaming API with access token

### ISSUE THREAD

**Issue by rollecode** [ronilaukkarinen/fedionfire#1]
Right now the token has only `read:statuses` permissions so no harm cannot be done by using it. But it is not a good thing to expose the API code anyway so need to figure out a better way to do this.

**Comment by Ry3yr** [comment]
For aes encryption this is your friend


<!DOCTYPE html>
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
</head>
<body>
  <script>
    const accessToken = "accesstoken";
    const secretKey = "firehose";
    const encryptedToken = CryptoJS.AES.encrypt(accessToken, secretKey).toString();
    const encryptedTokenElement = document.createElement("p");
    encryptedTokenElement.textContent = encryptedToken;
    document.body.appendChild(encryptedTokenElement);
    const evtSource = new EventSource(`https://mastodon.social/api/v1/streaming/public?access_token=${encryptedToken}`);
  </script>
</body>
</html>

It also salts it afaics
Regrettably we can't have the passphrase out in the open like that.
(Which is an issue when trying to access the accesstoken from the aes... Kind of a catch22)

Pagecrypt by Max (AES) requires a defacto password entry, but asking ppl to enter a password is out of question.

Maybe if a php could supply the token from outside ?
Their (non html component) code cannot be viewed.

**Comment by rollecode** [comment]
Thanks for the thoughts. Yes, doesn’t really solve the fact it’s out in the open.

> Maybe if a php could supply the token from outside

Thought about this, but don’t know yet how to pass it to the event stream.
