### ISSUE TITLE
Respect "delete" events

### ISSUE THREAD

**Issue by ThisIsMissEm** [ronilaukkarinen/fedionfire#2]
I mentioned this on Mastodon, but just to be absolutely certain it gets addressed: the streaming API doesn't just contain events of new stuff being posted. Every event sent contains a type, which indicates specific expected behaviour for the consumer.

One of these event types is deletes, which are issued when a user deletes their post: currently Fedionfire does not respect these delete events, which should remove the post from the output.

you'll also want to make sure you're respecting `status.update` too, not just update. `status.update` says "the status with this ID has been edited & therefore it should be updated in the UI"

This gives you three events you should listen to: update, status.update and delete. The other's aren't relevant for your use-case.

https://docs.joinmastodon.org/methods/streaming/#events

**Comment by rollecode** [comment]
Thanks. I’ll implement it as soon as possible.

**Comment by rollecode** [comment]
Would @raikasdev be willing to help me with this? 🙏🥺

**Comment by raikasdev** [comment]
👍 Will look into it today

**Comment by rollecode** [comment]
> 👍 Will look into it today

You're golden, saving my day as usual ❤️
