### ISSUE TITLE
Use relays instead of Streaming API

### ISSUE THREAD

**Issue by rollecode** [ronilaukkarinen/fedionfire#3]
> The better way to develop something like this is to use the Relay's functionality, instead of the streaming API.
> 
> By using the Relay's API, you'd also be needed to add in a privacy policy to document how data is stored, handled, distributed and secured.
> 
> For a bit of background, take a look at this ticket: ‪https://github.com/mastodon/mastodon/issues/24116

**Comment by rollecode** [comment]
@ThisIsMissEm Can you give me a hint on where to start with this? Streaming API is now a bit familiar to me, but I can't seem to find documentation about Relay API anywhere.

I'm now going to ask a very newbie question, since I don't know enough about this. How to fetch data from relays via EventSource or something similar? I need some head start.

**Comment by ThisIsMissEm** [comment]
So a "relay" is just any automated service instance; essentially they are added by an admin, and then receive content via activitypub. This has a bit more information: https://joinfediverse.wiki/index.php?title=Fediverse_relays&mobileaction=toggle_view_desktop

**Comment by ThisIsMissEm** [comment]
You could also talk to @astro who's behind FediBuzz.

**Comment by astro** [comment]
#FediBuzz not only consumes Mastodon's streaming API but also serves it: https://fedi.buzz/api/v1/streaming/public

**Comment by rollecode** [comment]
Oh I see! Thanks. Definitely helpful. I mistakenly thought there is a thing called Relay, but now I get it. Will probably get more energy first and then get more focused on this… Thanks again. 🫶

**Comment by rollecode** [comment]
Closing this in favor of #4.
