### ISSUE TITLE
Include more sources than just mastodon.social

### ISSUE THREAD

**Issue by rollecode** [ronilaukkarinen/fedionfire#4]
I have no idea how to implement this and maybe using relays is the answer (#3), but [mastodon-firehose](https://github.com/cscape/mastodon-firehose) has done this in the past. It would be a blast to see as much sources as possible, since mastodon.social is just a start.

**Comment by raikasdev** [comment]
Fedi.buzz provides a Mastodon compatible streaming API at https://fedi.buzz/api/v1/streaming/public

It just doesn't have CORS, so using corsproxy.io the streaming API url would be `https://corsproxy.io/?https%3A%2F%2Ffedi.buzz%2Fapi%2Fv1%2Fstreaming%2Fpublic`.

@astro is adding CORS headers to Fedi.buzz streaming API possible?

**Comment by astro** [comment]
Could you instead redistribute that feed yourself so that I don't have to serve every one of your visitors? #FediBuzz has no budget.

**Comment by raikasdev** [comment]
Good point.

**Comment by raikasdev** [comment]
@ronilaukkarinen: a possibility could be to host an [buzzrelay](https://github.com/astro/buzzrelay) instance (with for example fedi.buzz streaming API), then reverse proxy that with CORS headers for the service. Or code some other proxy that only uses a single connection the fedi.buzz streaming API to avoid stressing it.

**Comment by rollecode** [comment]
Okay I have the relay set up at relay.fireonfedi.stream, that seems to be now similar to relay.fedi.buzz, running on port 3000. But how can I stream that content via my relay? Is the source of fedi.buzz available somewhere? @astro @raikasdev

**Comment by raikasdev** [comment]
Doesn't seem like it 🤔

A possibility is to write a custom proxy that listens to fedi.buzz with a single socket and serves the events to fedionfire users to avoid stressing FediBuzz. Node, [Bun](https://bun.sh)? PHP probably won't do it as the socket needs to be persistent and a single one for all.

**Comment by rollecode** [comment]
Perhaps. But I'm not familiar with it at all, don't even know where to start :( So help needed here.

**Comment by astro** [comment]
Run buzzrelay with the fedi.buzz streaming API just like in the example config.yaml. Point a HTTPS reverse proxy at this port 3000. Then following should work.

**Comment by rollecode** [comment]
I did that but https://relay.fedionfire.stream/api/v1/streaming/public doesn't work that way. Also right now https://relay.fedionfire.stream returns 404 for some reason even though it's running... weird.

**Comment by astro** [comment]
Something seems to be broken in your reverse proxy setup.

**Comment by raikasdev** [comment]
I did not find the streaming endpoint in the source code, are you sure that the relay contains the code for the Streaming API compatible endpoints?

**Comment by astro** [comment]
buzzrelay connects to the streaming API endpoint, it doesn't serve it.

**Comment by raikasdev** [comment]
That's the point. We are trying to setup an own streaming API endpoint, like fedi.buzz/api/v1/streaming/public, not relay.fedi.buzz/...
